### ISSUE TITLE
Usage with React

### ISSUE THREAD

**Issue by remjx** [lqez/autocrop.js#1]
I am trying to use this with React but it's not working for me. Here is a CodeSandbox exhibiting the issue: 

https://codesandbox.io/s/autocrop-zuxgi?file=/src/Image.js

Any help would be greatly appreciated.

**Comment by lqez** [comment]
I got the error message while running the above example site and it turned out as a CORS error.
```
(index):1 Access to image at 'https://i.ytimg.com/vi/jjrYYqa0CCs/hqdefault.jpg' from origin 'https://el25o.csb.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

And I ran it on demo site with the same image and given parameters, it worked well.
<img width="527" alt="Screen Shot 2020-08-25 at 11 50 51 AM" src="https://user-images.githubusercontent.com/579366/91117314-45acf800-e6c9-11ea-8759-293f00f98d34.png">

But it seems that you don't need to add a margin, so I suggest you to use below parameters.
```
{
  bgColor: "#000000",
  colorTolerance: 50,
  margin: "0%",
  marker: "cropped"
}
```
<img width="516" alt="Screen Shot 2020-08-25 at 11 49 45 AM" src="https://user-images.githubusercontent.com/579366/91117373-65dcb700-e6c9-11ea-86b0-4363ffe9df59.png">

**Comment by remjx** [comment]
@lqez Thanks for your reply! Did you run it in React? The CodeSandbox is not generating any errors in the console and the original image loads, but the newly cropped image does not replace it. Can you please reopen this issue since it is not resolved?

**Comment by lqez** [comment]
@markjackson02 I knew that your sandbox code is still not working. But this issue seems not to be up to autocrop.js itself.
Please test it on local React env with local images and reopen this if you get same problem on it.
